#!/bin/bash
foreground=$1
background=$2
font=$3

# Check to see if external is connected
if [[ -z `xrandr | grep " connected" | grep 'VGA'` ]]; then
	conky -qc /home/sunn/.xmonad/.conky_dzen | dzen2 -x '766' -w '600' -h '14' -ta 'r' -bg $background -fg $foreground -y '0' -fn $font -dock &
	conky -qc /home/sunn/.xmonad/.conky_dzen1 | dzen2 -x '0' -w '300' -h '14' -ta 'l' -bg $background -fg $foreground -y '0' -fn $font -dock &
else 
	#nitrogen --restore
	conky -qc /home/sunn/.xmonad/.conky_dzen | dzen2 -x '1200' -w '720' -h '14' -ta 'r' -bg $background -fg $foreground -y '0' -fn $font -dock &
	conky -qc /home/sunn/.xmonad/.conky_dzen1 | dzen2 -x '0' -w '720' -h '14' -ta 'l' -bg $background -fg $foreground -y '0' -fn $font -dock &
	#conky -qc /home/sunn/.xmonad/.conky_dzen2 | dzen2 -x '1200' -w '720' -h '14' -ta 'r' -bg $background -fg $foreground -y '0' -fn $font -dock &
	#conky -qc /home/sunn/.xmonad/.conky_dzen3 | dzen2 -x '1200' -w '720' -h '14' -ta 'r' -bg $background -fg $foreground -y '0' -fn $font -dock &
fi
