#!/bin/sh
# These things are run when an Openbox X Session is started.
# You may place a similar script in $HOME/.config/openbox/autostart
# to run user-specific things.
#

# If you want to use GNOME config tools...
#
#if test -x /usr/lib/openbox/gnome-settings-daemon >/dev/null; then
#  /usr/lib/openbox/gnome-settings-daemon &
#elif which gnome-settings-daemon >/dev/null; then
#  gnome-settings-daemon &
#fi

#/home/sunn/.config/openbox/panel.sh &
compton -cCfb -D 3.5 &
conky -qc ~/.config/openbox/conky_config &
docky &
hsetroot -fill ~/Pictures/Jaws.jpg &
xfce4-panel &
#trayer --edge top --align right --margin 5 --widthtype pixel --width 350 --heighttype pixel --height 20 --SetDockType false --SetPartialStrut true --transparent true --alpha 255
