#!/bin/sh

WIDTH=85
#FONT="-artwiz-limey-medium-r-normal-*-10-110-75-75-m-50-iso8859-*"
#FONT='sans:size=11'
#FONT='sawasdee:size=10'
#FONT='-*-gohufontmod11-*-*-*-*-*-*-*-*-*-*-*-*'
#FONT='-*-suxus-*-*-normal-*-10-100-75-75-c-50-iso8859-1'
#FONT='-*-nu-*-*-normal-*-10-100-75-75-c-50-iso8859-1'
FONT='-*-tewi-medium-*-normal-*-*-*-*-*-*-*-*-*'


# Width of the graphical separator (default 80% of window's width)
SEPARATOR_WIDTH=`expr $WIDTH - \( $WIDTH / 100 \) \* 20`

#Position
X=48
Y=0

MENUFILE=$1

# number of visible menu entries (access the others through scrolling up/down)
LINES=`wc -l "$MENUFILE"|sed -e 's/ .*//'`
[ $LINES -gt 20 ] && LINES=20

execute () {
	read PROG

	while read LINE; do 
		LBL=;APP=
		LBL=$(echo $LINE|sed -e 's/:.*$//' -e 's/^[ \t]*//' -e 's/[ \t]*$//')
		APP=$(echo $LINE|sed -e 's/^.*://' -e 's/^[ \t]*//' -e 's/[ \t]*$//')

		if [ x"$APP" = x"exit" ]; then
			exit
		elif [ x"$LBL" = x"$PROG" ]; then
			if [ x"$APP" = x"" ]; then
				$LBL&
			else
				$APP&
			fi
			exit
		fi
	done < "$MENUFILE"
}


(
echo " "   
sed -e 's/:.*$//' \
	-e 's/^.--*/^r('${SEPARATOR_WIDTH}'x1)/' "$MENUFILE" 
) | \
	dzen2 -tw 1 -l $LINES -w $WIDTH -x $X -y $Y -fn $FONT -bg '#181512' -fg '#9a875f' -p -m -sa l -e 'onstart=uncollapse;leaveslave=exit;button1=menuprint_noparse,exit' | execute
