#!/bin/bash

source $(dirname $0)/config

# Only run if mpd is running
if [ $(pgrep -cx mpd) -eq 0 ] ; then
	exit 1
fi

err() {
	echo "$1"
	exit 1
}

usage() {
	echo "usage: notify_mpd [option]"
	echo
	echo "Options:"
	echo "  -n, --next    - next track"
	echo "  -p, --prev    - previous track"
	echo "  -t, --toggle  - toggle pause"
	echo "  -d, --daemon  - listen for track changes through mpd frontends"
	echo "  -h, --help    - display this"
	exit
}


notify() {
	$(dirname $0)/notify "$@" &
}

state() {
	mpc | sed -n 's/^.*\[\([^\[].*\)\] .*$/\1/p' | uniq
}

case $1 in
	'-p'|'--prev')
		mpc prev
		icon=
	;;
	'-n'|'--next')
		mpc next
		icon=
	;;
	'-t'|'--toggle')
		mpc toggle
		if [[ `state` == 'paused' ]]; then
			icon=
		elif [[ `state` == 'playing' ]]; then
			icon=
		fi
	;;
	'-d'|'--daemon')
		while true; do
			infos=$(mpc current --wait)
			notify	 $infos
		done
	;;
	''|'-h'|'--help')
		usage
	;;
	*)
		err "Unrecognized option \`$1', see notify_mpd --help"
esac

notify  $icon $(mpc current)
