#!/bin/sh
#
# z3bra - (c) wtfpl 2014
# Manage ALSA Master channel

source $(dirname $0)/config

test "$1" = "-h" && echo "usage `basename $0` [+|-|!]" && exit 0

level() {
    amixer get Master | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p' | uniq
}

state() {
    amixer get Master | sed -n 's/^.*\[\(o[nf]\+\)]$/\1/p' | uniq
}

test $# -eq 0 && echo "`level` `state`" && exit 0

case $1 in
    +)      amixer set Master 3%+ >/dev/null;; 
    -)      amixer set Master 3%- >/dev/null;;
    !)      amixer set Master toggle >/dev/null;;
    state|level) $1;;
    *)    amixer set Master $1 >/dev/null;;
esac


if [[ `state` != "on" ]]; then
	icon=""
elif [[ `level` -lt 30 ]]; then
	icon=""
else
	icon=""
fi
steps=$(echo "100/$BAR_LENGTH" | bc)
current=$(echo "`level`/$steps" | bc)
for i in `seq 1 $BAR_LENGTH`;
do
	if [[ `state` != "on" ]]; then
		bar+=" "
	elif [ $i -lt $current ]; then
		bar+="%{F$COLOR_ACTIVE}-%{F-}"
	else
		bar+="%{F$COLOR_OCCUPIED}-%{F-}"
	fi
done

$(dirname $0)/notify  $icon $bar&
mplayer "$CLIP" >/dev/null&
