#! /bin/sh

cd $(dirname $0)
source $(dirname $0)/config

if [ $(pgrep -x panel | wc -l) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &
while true; do echo "S$(source panel_dzen)" > "$PANEL_FIFO"; sleep 2; done &
while true; do echo "C$(date +%r)" > "$PANEL_FIFO"; sleep 2; done &
echo "S" > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | ./panel_dzen2 -f $FONT2 | dzen2 -x 0 -y -1 -ta l -bg $COLOR_BACKGROUND -fg $COLOR_FOREGROUND  -fn $FONT1 -h $PANEL_HEIGHT &
#cat "$PANEL_FIFO" | /usr/local/Cellar/bar-aint-recursive/master/bin/bar/bar -F "#FFFF0000" -B "#FFFFFFFF" -b -g "1000x14+0+0" -f "$FONT1","$FONT2" -d
wait
