#! /bin/sh
#
# Example panel for LemonBoy's bar

while read -r line ; do
    case $line in
        S*)
            sys_infos="%{r}${line#?}"
            ;;
        T*)
            title="  bspwm"
            ;;
        W*)
            wm_infos="%{c}"
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    [OFU]*)
                        # active desktop
                        wm_infos="$wm_infos%{U#FF0000000}%{+u}   %{-u}"
                        ;;
                    o*)
                        # inactive but occupied desktop
                        wm_infos="$wm_infos%{U#FFD8D8D8}%{+u}   %{-u}"
                        ;;
                    f*)
                        # inactive desktop
                        wm_infos="$wm_infos   "
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos%{U#FFC58BFF}%{+u}   %{-u}"
                        ;;
                    L*)
                        # layout
#                        layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
                        wm_infos="$wm_infos $layout"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "$title$wm_infos$sys_infos"
done
