#! /bin/sh
#
# Example panel for LemonBoy's bar

while read -r line ; do
    case $line in
        S*)
            sys_infos="\\r${line#?}\\fr"
            ;;
        T*)
            title="\\f8  \\f9 bspwm"
            ;;
        W*)
            wm_infos="\\c"
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    [OFU]*)
                        # active desktop
                        wm_infos="$wm_infos\\f9 • \\fr\\br"
                        ;;
                    o*)
                        # inactive but occupied desktop
                        wm_infos="$wm_infos\\f8 • \\fr"
                        ;;
                    f*)
                        # inactive desktop
                        wm_infos="$wm_infos\\f8 ○ \\fr"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos \\f3•\\fr "
                        ;;
                    L*)
                        # layout
#                        layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
			layout=""
                        wm_infos="$wm_infos \\b4\\f0$layout\\br\\fr"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "$title $wm_infos $sys_infos"
done
