#! /bin/sh

FIRST_DESK_MAIN=i
REMAINING_DESKS_MAIN="ii iii iv v vi vii viii ix x"
FIRST_DESK_SECONDARY=I
REMAINING_DESKS_SECONDARY="II III IV V VI VII VIII IX X"


if [[ -z `xrandr | grep " connected" | grep 'VGA'` ]]; then
	echo "No monitor connected"
	bspc desktop Desktop01 -n $FIRST_DESK_MAIN
	bspc monitor -a $REMAINING_DESKS_MAIN
	bspc monitor -p 14 0 0 0
else
	bspc desktop Desktop01 -n $FIRST_DESK_SECONDARY
	bspc monitor -a $REMAINING_DESKS_SECONDARY
	bspc monitor -p 0 0 0 0

	bspc monitor -f next
	bspc desktop Desktop02 -n $FIRST_DESK_MAIN
	bspc monitor -a $REMAINING_DESKS_MAIN
	bspc monitor -p 14 0 0 0
fi

bspc config split_ratio         0.52
bspc config border_width        2
bspc config window_gap          4
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config focused_border_color #646a6d
bspc config normal_border_color #322d29

bspc rule -a Thunar --floating
bspc rule -a Skype --floating
bspc rule -a Transmission --floating
bspc rule -a feh --floating
bspc rule -a Gimp -d Eight --floating

panel &
/home/sunn/.xmonad/status_bar "#d6c3b6" "#181512" "-*-nu-*-*-*-*-*-*-*-*-*-*-*-*" &
