#! /bin/sh

#if [ -e "$BSPWM_TREE" ] ; then
#	bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
#	    rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
#fi

FIRST_DESK_MAIN=i
REMAINING_DESKS_MAIN="ii iii iv v vi vii viii ix x"
FIRST_DESK_SECONDARY=I
REMAINING_DESKS_SECONDARY="II III IV V VI VII VIII IX X"

MONITORS_ASSOCIATED=`bspc query -M | wc -l` 
if [[ -z `xrandr | grep " connected" | grep 'VGA'` ]]; then
	#No monitor connected
	bspc desktop ^1 -n $FIRST_DESK_MAIN
	bspc monitor -a $REMAINING_DESKS_MAIN
	bspc config top_padding 14
else
	bspc desktop ^1 -n $FIRST_DESK_SECONDARY
	bspc monitor -a $REMAINING_DESKS_SECONDARY

	bspc monitor -f next

	bspc desktop Desktop2 -n $FIRST_DESK_MAIN
	bspc monitor -a $REMAINING_DESKS_MAIN
	bspc config -m VGA1 top_padding 14
fi

# Visual options
bspc config split_ratio         0.50
bspc config border_width        2
bspc config window_gap          12
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#504339"
bspc config active_border_color "#504339"
bspc config focused_border_color "#605655"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#504339"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.05
bspc config rule_command "$(which rule_command)"


# Rules
rulc -a 'class=="BSPWM_FRAME"' 'frame=on'
rulc -a 'class=="Skype"' 'floating=on'
rulc -a 'class=="Transmission"' 'floating=on'
rulc -a 'class=="Conky"' 'sticky=on,manage=off,lower=on'
rulc -a 'class=="astime"' 'sticky=on'
rulc -a 'class=="feh"' 'floating=on,manage=off'

/home/sunn/.config/bspwm/panel/panel &
