#! /bin/sh
#
# Example panel for LemonBoy's bar

while read -r line ; do
    case $line in
        S*)
            sys_infos="\\r\\f5${line#?}\\fr"
            ;;
        T*)
#            title="\\c${line#?}"
            title=""
            ;;
        W*)
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    [OFU]*)
                        # active desktop
                        wm_infos="$wm_infos\\u9\\f1 ${name} \\fr\\br\\ur"
                        ;;
                    o*)
                        # inactive but occupied desktop
                        wm_infos="$wm_infos\\f6 ${name} \\fr"
                        ;;
                    f*)
                        # inactive desktop
                        wm_infos="$wm_infos\\f2 ${name} \\fr"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos \\u3\\f6${name}\\ur\\fr "
                        ;;
                    L*)
                        # layout
#                        layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
			layout=""
                        wm_infos="$wm_infos \\b4\\f0$layout\\br\\fr"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "$wm_infos $title $sys_infos"
done
