// Generated by CoffeeScript 1.3.3
(function() {
  var Settings, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Settings = Settings = {
    get: function(key) {
      if (key in localStorage) {
        return JSON.parse(localStorage[key]);
      } else {
        return this.defaults[key];
      }
    },
    set: function(key, value) {
      if (value === this.defaults[key]) {
        return this.clear(key);
      } else {
        return localStorage[key] = JSON.stringify(value);
      }
    },
    clear: function(key) {
      return delete localStorage[key];
    },
    has: function(key) {
      return key in localStorage;
    },
    defaults: {
      scrollStepSize: "60",
      linkHintCharacters: "sadfjklewcmpgh",
      filterLinkHints: false,
      hideHud: false,
      userDefinedLinkHintCss: "div > .vimiumHintMarker {\n/* linkhint boxes */\nbackground: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#FFF785),\n  color-stop(100%,#FFC542));\nborder: 1px solid #E3BE23;\n}\n\ndiv > .vimiumHintMarker span {\n/* linkhint text */\ncolor: black;\nfont-weight: bold;\nfont-size: 12px;\n}\n\ndiv > .vimiumHintMarker > .matchingCharacter {\n}",
      excludedUrls: "http*://mail.google.com/*\nhttp*://www.google.com/reader/*",
      previousPatterns: "prev,previous,back,<,\u2190,\xab,\u226a,<<",
      nextPatterns: "next,more,>,\u2192,\xbb,\u226b,>>",
      searchUrl: "http://www.google.com/search?q="
    }
  };

  Settings.set("settingsVersion", Utils.getCurrentVersion());

}).call(this);
